### PR TITLE
Noetic devel

### PR DESCRIPTION
**Pull request by NiklasRolleberg**
* The captain interface has been changed. The communication between the captain and the scientist is using UDP instead of TCP
* SetBool services added to toggle control inputs on the captain
* Captain ip added as a variable in lolo_bringup

### CODE REVIEW

**Comment by nilsbore** [comment]
Looks good, since it passes, I'll merge unless you want me hold off @NiklasRolleberg

**Comment by NiklasRolleberg** [comment]
I found a few more things from the common interface that is missing, so you can hold off for a few days until I have added those

**Comment by nilsbore** [comment]
Ok! What's the reason for switching to UDP?

**Comment by NiklasRolleberg** [comment]
It will hopefully make the interface more stable. We had a problem where the Ethernet port on the captain would crash if it was listening for TCP connections. This issue seemed to go away if the captain connected to the scientist, so that's how it was implemented before. Using UDP seemed like a better choice since we could stop using TCP entierly, and we can also let the scientist initiate the communication to the captain, which makes it more convenient if the scientist were to change IP for some reason.

**Comment by nilsbore** [comment]
Just FYI, I used `/lolo/core/rudder_cmd`, `/lolo/core/elevator_cmd`, `/lolo/core/elevon_port_cmd` and `/lolo/core/elevon_strb_cmd` as `std_msgs::Float32` in the simulator, just as you had it on Lolo. Please let me know if you change those.

**Comment by NiklasRolleberg** [comment]
Sure I can change that

**Comment by nilsbore** [comment]
Aha, I didn't even realize you had changed it. Great, now we should have the same interface!

**Comment by nilsbore** [comment]
As a bonus you can now use the web interface: https://github.com/smarc-project/lolo_webgui or the native gui. Install either from the smarc package releases.

**Pull request merged**
